CC = gcc
CFLAGS = -Wall -Wextra -Werror -pedantic

test0:
	$(CC) $(CFLAGS) 0-main.c
	./a.out
	rm a.out

test1:
	$(CC) $(CFLAGS) 1-main.c
	./a.out
	rm a.out

test2:
	$(CC) $(CFLAGS) 2-main.c
	./a.out
	rm a.out

test2.1:
	$(CC) $(CFLAGS) 2-main_malloc.c
	./a.out
	rm a.out

test3:
	$(CC) $(CFLAGS) 3-main.c
	./a.out
	rm a.out

test4:
	$(CC) $(CFLAGS) 4-main.c
	./a.out
	rm a.out

test4.1:
	$(CC) $(CFLAGS) sysconf.c
	./a.out
	rm a.out

test4.2:
	$(CC) $(CFLAGS) 4-main_beyond.c
	./a.out
	rm a.out

test5:
	$(CC) $(CFLAGS) 5-main.c
	./a.out
	rm a.out

test6:
	$(CC) $(CFLAGS) 6-main.c
	./a.out
	rm a.out
